#!/usr/bin/env python3
from pathlib import Path
import re
import sys

root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path('.')
imp_path = root / 'includes/class-asss-importer.php'
main_path = root / 'all-star-supplier-sync.php'
readme_path = root / 'readme.txt'
imp = imp_path.read_text()
main = main_path.read_text()
readme = readme_path.read_text()


def replace_once(text, old, new, label):
    if old not in text:
        raise SystemExit(f'Missing patch anchor: {label}')
    return text.replace(old, new, 1)

# Version.
main = main.replace('Version: 2.0.16', 'Version: 2.0.17', 1)
main = main.replace("define('ASSS_VERSION', '2.0.16');", "define('ASSS_VERSION', '2.0.17');", 1)
readme = readme.replace('Stable tag: 2.0.15', 'Stable tag: 2.0.17', 1)
changelog = '''= 2.0.17 =
* Unified storefront-vs-reference media policy across SanMar, S&S Activewear, and Momentec.
* Supplier swatch sheets, color boards/chips, charts, unknown asset types, and Momentec alternate media are retained as supplier reference metadata but excluded from WooCommerce featured/product/variation galleries.
* SanMar COLOR_SWATCH_IMAGE is no longer imported into the customer-facing product gallery.
* SanMar featured media now prefers real product photography before generic product imagery.
* Momentec galleries now trust only known photographic view types; alternate/unknown media stays reference-only.
* Quick Repair/refresh removes previously imported Supplier Sync-owned reference graphics while preserving merchant-added featured/gallery images.

'''
readme = readme.replace('== Changelog ==\n\n', '== Changelog ==\n\n' + changelog, 1)

# Generic supplier reference metadata helper, used by every supplier.
anchor = '''    private function is_supplier_attachment(int $attachment_id): bool {
        if ($attachment_id < 1) return false;
        if ((string)get_post_meta($attachment_id, '_asss_image_url', true) !== '') return true;
        return in_array((string)get_post_meta($attachment_id, '_asss_image_source', true), ['sanmar','ss','momentec','supplier'], true);
    }

'''
helper = anchor + '''    /** Store supplier-only visual references without exposing them in Woo galleries. */
    private function save_supplier_reference_media(int $post_id, string $supplier, array $urls): void {
        $supplier = sanitize_key($supplier) ?: 'supplier';
        $clean = [];
        foreach ($urls as $raw) {
            $url = trim((string)$raw);
            if ($supplier === 'ss') $url = $this->normalize_ss_media_url($url);
            elseif ($supplier === 'momentec') $url = $this->momentec_media_url($url);
            else $url = filter_var($url, FILTER_VALIDATE_URL) ? esc_url_raw($url) : '';
            if ($url !== '') $clean[$url] = true;
        }
        $key = '_asss_' . $supplier . '_reference_media_urls';
        if ($clean) update_post_meta($post_id, $key, wp_json_encode(array_keys($clean)));
        else delete_post_meta($post_id, $key);
    }

'''
imp = replace_once(imp, anchor, helper, 'reference metadata helper')

# Make the existing S&S helper use the shared storage path.
old = '''    private function save_ss_reference_media(int $post_id, array $urls): void {
        $clean = [];
        foreach ($urls as $raw) {
            $url = $this->normalize_ss_media_url((string)$raw);
            if ($url !== '') $clean[$url] = true;
        }
        if ($clean) update_post_meta($post_id, '_asss_ss_reference_media_urls', wp_json_encode(array_keys($clean)));
        else delete_post_meta($post_id, '_asss_ss_reference_media_urls');
    }
'''
new = '''    private function save_ss_reference_media(int $post_id, array $urls): void {
        $this->save_supplier_reference_media($post_id, 'ss', $urls);
    }
'''
imp = replace_once(imp, old, new, 'S&S shared reference helper')

# SanMar variation gallery: never use explicit reference assets as fallbacks.
old = '''    private function variation_gallery_urls(array $row): array {
        $urls = [];

        // Prefer the explicit ordered gallery generated by GitHub when present.
        $raw_gallery = $this->sanmar->first($row, ['VARIATION_GALLERY_URLS']);
        if (is_string($raw_gallery) && trim($raw_gallery) !== '') {
            $decoded = json_decode($raw_gallery, true);
            if (is_array($decoded)) {
                foreach ($decoded as $url) {
                    $url = trim((string)$url);
                    if ($url && filter_var($url, FILTER_VALIDATE_URL)) $urls[$url] = true;
                }
            }
        }

        // Reconstruct from named feed fields too. This keeps local/direct feeds,
        // older cached bridge payloads, and future suppliers compatible.
        foreach ([
            'COLOR_PRODUCT_IMAGE', // best color-specific hero when supplied
            'FRONT_FLAT',
            'FRONT_MODEL',
            'THREE_Q_MODEL',
            'SIDE_MODEL',
            'BACK_MODEL',
            'BACK_FLAT',
        ] as $key) {
            $url = trim((string)$this->sanmar->first($row, [$key]));
            if ($url && filter_var($url, FILTER_VALIDATE_URL)) $urls[$url] = true;
        }

        // Lower-resolution/generic fallbacks are used only if SanMar did not
        // supply a usable color-specific full image set.
        if (!$urls) {
            foreach (['COLOR_PRODUCT_IMAGE_THUMBNAIL','PRODUCT_IMAGE','THUMBNAIL_IMAGE'] as $key) {
                $url = trim((string)$this->sanmar->first($row, [$key]));
                if ($url && filter_var($url, FILTER_VALIDATE_URL)) $urls[$url] = true;
            }
        }
        return array_keys($urls);
    }
'''
new = '''    private function variation_gallery_urls(array $row): array {
        $urls = [];
        $reference = [];
        foreach (['COLOR_SWATCH_IMAGE','COLOR_SQUARE_IMAGE'] as $key) {
            $url = trim((string)$this->sanmar->first($row, [$key]));
            if ($url && filter_var($url, FILTER_VALIDATE_URL)) $reference[$url] = true;
        }

        // Prefer the explicit ordered gallery generated by GitHub when present,
        // but strip any URL that is also identified as supplier reference media.
        $raw_gallery = $this->sanmar->first($row, ['VARIATION_GALLERY_URLS']);
        if (is_string($raw_gallery) && trim($raw_gallery) !== '') {
            $decoded = json_decode($raw_gallery, true);
            if (is_array($decoded)) {
                foreach ($decoded as $url) {
                    $url = trim((string)$url);
                    if ($url && !isset($reference[$url]) && filter_var($url, FILTER_VALIDATE_URL)) $urls[$url] = true;
                }
            }
        }

        foreach ([
            'COLOR_PRODUCT_IMAGE','FRONT_FLAT','FRONT_MODEL','THREE_Q_MODEL',
            'SIDE_MODEL','BACK_MODEL','BACK_FLAT',
        ] as $key) {
            $url = trim((string)$this->sanmar->first($row, [$key]));
            if ($url && !isset($reference[$url]) && filter_var($url, FILTER_VALIDATE_URL)) $urls[$url] = true;
        }

        if (!$urls) {
            foreach (['COLOR_PRODUCT_IMAGE_THUMBNAIL','PRODUCT_IMAGE','THUMBNAIL_IMAGE'] as $key) {
                $url = trim((string)$this->sanmar->first($row, [$key]));
                if ($url && !isset($reference[$url]) && filter_var($url, FILTER_VALIDATE_URL)) $urls[$url] = true;
            }
        }
        return array_keys($urls);
    }
'''
imp = replace_once(imp, old, new, 'SanMar variation reference filter')

# SanMar parent gallery: swatches are reference-only and old supplier swatches get cleaned on repair.
old = '''    private function sync_parent_media(int $product_id, array $row): void {
        $product = wc_get_product($product_id);
        if (!$product) return;

        $featured_url = (string)$this->sanmar->first($row, ['PRODUCT_IMAGE','FRONT_FLAT','COLOR_PRODUCT_IMAGE']);
        if ($featured_url) {
            $current = $product->get_image_id();
            if (!$current || get_post_meta($current, '_asss_image_source', true) === 'sanmar') {
                $aid = $this->sideload($featured_url, $product_id);
                if ($aid) $product->set_image_id($aid);
            }
        }

        $gallery_urls = [];
        foreach (['FRONT_FLAT','BACK_FLAT','FRONT_MODEL','BACK_MODEL','SIDE_MODEL','THREE_Q_MODEL','COLOR_SWATCH_IMAGE'] as $key) {
            $url = trim((string)$this->sanmar->first($row, [$key]));
            if ($url && $url !== $featured_url) $gallery_urls[$url] = true;
        }

        $supplier_gallery = [];
        foreach (array_keys($gallery_urls) as $url) {
            $aid = $this->sideload($url, $product_id);
            if ($aid) $supplier_gallery[] = $aid;
        }

        $manual_gallery = [];
        foreach ($product->get_gallery_image_ids() as $id) {
            if (get_post_meta($id, '_asss_image_source', true) !== 'sanmar') $manual_gallery[] = (int)$id;
        }
        $product->set_gallery_image_ids(array_values(array_unique(array_merge($supplier_gallery, $manual_gallery))));
        $product->save();
    }
'''
new = '''    private function sync_parent_media(int $product_id, array $row): void {
        $product = wc_get_product($product_id);
        if (!$product) return;

        $reference = [];
        foreach (['COLOR_SWATCH_IMAGE','COLOR_SQUARE_IMAGE'] as $key) {
            $url = trim((string)$this->sanmar->first($row, [$key]));
            if ($url && filter_var($url, FILTER_VALIDATE_URL)) $reference[$url] = true;
        }
        $this->save_supplier_reference_media($product_id, 'sanmar', array_keys($reference));

        $featured_url = '';
        foreach (['FRONT_FLAT','COLOR_PRODUCT_IMAGE','PRODUCT_IMAGE','THUMBNAIL_IMAGE'] as $key) {
            $candidate = trim((string)$this->sanmar->first($row, [$key]));
            if ($candidate && !isset($reference[$candidate]) && filter_var($candidate, FILTER_VALIDATE_URL)) {
                $featured_url = $candidate;
                break;
            }
        }
        if ($featured_url !== '') {
            $current = (int)$product->get_image_id();
            if (!$current || get_post_meta($current, '_asss_image_source', true) === 'sanmar') {
                $aid = $this->sideload($featured_url, $product_id, 'sanmar');
                if ($aid) $product->set_image_id($aid);
            }
        }

        $gallery_urls = [];
        foreach (['FRONT_FLAT','COLOR_PRODUCT_IMAGE','BACK_FLAT','FRONT_MODEL','BACK_MODEL','SIDE_MODEL','THREE_Q_MODEL','PRODUCT_IMAGE','THUMBNAIL_IMAGE'] as $key) {
            $url = trim((string)$this->sanmar->first($row, [$key]));
            if ($url && $url !== $featured_url && !isset($reference[$url]) && filter_var($url, FILTER_VALIDATE_URL)) $gallery_urls[$url] = true;
        }

        $supplier_gallery = [];
        foreach (array_keys($gallery_urls) as $url) {
            $aid = $this->sideload($url, $product_id, 'sanmar');
            if ($aid) $supplier_gallery[] = $aid;
        }

        $manual_gallery = [];
        foreach ($product->get_gallery_image_ids() as $id) {
            $id = (int)$id;
            if ($id && !$this->is_supplier_attachment($id)) $manual_gallery[] = $id;
        }
        $product->set_gallery_image_ids(array_values(array_unique(array_merge($supplier_gallery, $manual_gallery))));
        $product->save();
    }
'''
imp = replace_once(imp, old, new, 'SanMar parent media')

# Momentec classifier.
anchor = '''    private function momentec_media_url(string $url): string {
        $url=trim($url);
        return preg_match('#^https?://#i',$url) ? esc_url_raw($url) : '';
    }

'''
helper = anchor + '''    /** Known Momentec photographic views are storefront media; alternate/unknown assets are reference-only. */
    private function momentec_classify_variant_media(array $row): array {
        $storefront=[];$reference=[];
        $allowed=array_fill_keys(['hero','lquarter','front','leftside','rightside','back'],true);
        $images=is_array($row['images'] ?? null)?$row['images']:[];
        foreach (['heroImage','hero_image','lquarter','front','lside','left_side','rside','right_side','back'] as $key) {
            $url=$this->momentec_media_url((string)($images[$key] ?? ''));
            if($url!=='')$storefront[$url]=true;
        }
        $gallery=is_array($row['gallery'] ?? null)?array_values($row['gallery']):[];
        $types=is_array($row['gallery_types'] ?? null)?array_values($row['gallery_types']):[];
        foreach($gallery as $i=>$raw){
            $url=$this->momentec_media_url((string)$raw);if($url==='')continue;
            $kind=strtolower((string)preg_replace('/[^a-z0-9]+/i','',(string)($types[$i] ?? '')));
            if(isset($allowed[$kind]) || isset($storefront[$url]))$storefront[$url]=true;
            else $reference[$url]=true;
        }
        foreach((array)($row['reference_media'] ?? []) as $raw){$url=$this->momentec_media_url((string)$raw);if($url!=='')$reference[$url]=true;}
        $primary=$this->momentec_media_url((string)($row['primary_image'] ?? ''));
        if($primary!=='' && !isset($storefront[$primary]))$reference[$primary]=true;
        foreach(array_keys($storefront) as $url)unset($reference[$url]);
        return ['storefront'=>array_keys($storefront),'reference'=>array_keys($reference)];
    }

'''
imp = replace_once(imp, anchor, helper, 'Momentec classifier')

# Replace Momentec variation media sync with classified behavior.
pattern = re.compile(r"    private function sync_momentec_variation_media\(int \$variation_id,array \$row\): void \{.*?\n    \}\n\n    private function momentec_parent_featured_url", re.S)
match = pattern.search(imp)
if not match:
    raise SystemExit('Missing patch anchor: Momentec variation media function')
replacement = '''    private function sync_momentec_variation_media(int $variation_id,array $row): void {
        $v=wc_get_product($variation_id);if(!$v instanceof WC_Product_Variation)return;
        $classified=$this->momentec_classify_variant_media($row);
        $urls=array_values((array)$classified['storefront']);
        $this->save_supplier_reference_media($variation_id,'momentec',(array)$classified['reference']);
        $current=(int)$v->get_image_id();$manual_primary=$current && !$this->is_supplier_attachment($current);
        $manual_gallery=[];
        if(method_exists($v,'get_gallery_image_ids'))foreach((array)$v->get_gallery_image_ids() as $id)if((int)$id&&!$this->is_supplier_attachment((int)$id))$manual_gallery[]=(int)$id;
        if(!$urls){
            if(!$manual_primary)$v->set_image_id(0);
            if(method_exists($v,'set_gallery_image_ids'))$v->set_gallery_image_ids(array_values(array_unique($manual_gallery)));
            $full=$manual_primary?array_values(array_unique(array_merge([$current],$manual_gallery))):array_values(array_unique($manual_gallery));
            $v->update_meta_data('_asss_variation_gallery_ids',$full);$v->update_meta_data('_asss_variation_gallery_urls',[]);$v->update_meta_data('_asss_variation_gallery_supplier_count',0);$v->delete_meta_data('_asss_resolved_variation_image_url');$v->save();return;
        }
        $supplier_ids=[];foreach($urls as $url){$aid=$this->sideload($url,$variation_id,'momentec');if($aid)$supplier_ids[]=(int)$aid;}
        $supplier_ids=array_values(array_unique(array_filter($supplier_ids)));if(!$supplier_ids)return;
        if(!$manual_primary)$v->set_image_id($supplier_ids[0]);
        $primary=$manual_primary?$current:$supplier_ids[0];$extra=array_values(array_filter($supplier_ids,static fn($id)=>(int)$id!==(int)$primary));
        if(method_exists($v,'set_gallery_image_ids'))$v->set_gallery_image_ids(array_values(array_unique(array_merge($extra,$manual_gallery))));
        $full=$manual_primary?array_values(array_unique(array_merge([$current],$supplier_ids,$manual_gallery))):array_values(array_unique(array_merge($supplier_ids,$manual_gallery)));
        $v->update_meta_data('_asss_variation_gallery_ids',$full);$v->update_meta_data('_asss_variation_gallery_urls',$urls);$v->update_meta_data('_asss_variation_gallery_supplier_count',count($supplier_ids));$v->update_meta_data('_asss_resolved_variation_image_url',esc_url_raw($urls[0]));$v->save();
    }

    private function momentec_parent_featured_url'''
imp = imp[:match.start()] + replacement + imp[match.end():]

# Featured image respects reference classification while preserving requested priority.
pattern = re.compile(r"    private function momentec_parent_featured_url\(array \$data,array \$variants\): string \{.*?\n    \}\n\n    /\*\* Attach only one parent image", re.S)
match = pattern.search(imp)
if not match:
    raise SystemExit('Missing patch anchor: Momentec featured function')
replacement = '''    private function momentec_parent_featured_url(array $data,array $variants): string {
        $reference=[];$known_storefront=[];
        foreach((array)($data['reference_media'] ?? []) as $raw){$u=$this->momentec_media_url((string)$raw);if($u!=='')$reference[$u]=true;}
        foreach($variants as $row){if(!is_array($row))continue;$classified=$this->momentec_classify_variant_media($row);foreach((array)$classified['storefront'] as $u)$known_storefront[$u]=true;foreach((array)$classified['reference'] as $u)$reference[$u]=true;}
        foreach(array_keys($known_storefront) as $u)unset($reference[$u]);
        // 1) Product-level thumbnail, but never if classified as reference.
        $thumbnail=$this->momentec_media_url((string)($data['images']['thumbnail'] ?? ''));if($thumbnail!==''&&!isset($reference[$thumbnail]))return $thumbnail;
        // 2) First selected variation's verified product photograph.
        foreach($variants as $row){if(!is_array($row))continue;$classified=$this->momentec_classify_variant_media($row);$first=(string)(((array)$classified['storefront'])[0] ?? '');if($first!=='')return $first;}
        // 3) Product image only when it is not known reference media.
        $product=$this->momentec_media_url((string)($data['images']['product'] ?? ''));if($product!==''&&!isset($reference[$product]))return $product;
        // 4) Leave blank for merchant selection rather than promoting reference media.
        return '';
    }

    /** Attach only one parent image'''
imp = imp[:match.start()] + replacement + imp[match.end():]

# Momentec parent gallery classified and reference saved.
pattern = re.compile(r"    private function sync_momentec_parent_media\(int \$product_id,array \$data,array \$variants\): void \{.*?\n    \}\n\n    private function momentec_row_for_variation", re.S)
match = pattern.search(imp)
if not match:
    raise SystemExit('Missing patch anchor: Momentec parent media function')
replacement = '''    private function sync_momentec_parent_media(int $product_id,array $data,array $variants): void {
        $product=wc_get_product($product_id);if(!$product)return;
        $storefront=[];$reference=[];
        foreach((array)($data['reference_media'] ?? []) as $raw){$u=$this->momentec_media_url((string)$raw);if($u!=='')$reference[$u]=true;}
        foreach($variants as $row){
            if(!is_array($row))continue;$classified=$this->momentec_classify_variant_media($row);
            foreach((array)$classified['storefront'] as $u)$storefront[$u]=true;
            foreach((array)$classified['reference'] as $u)$reference[$u]=true;
            if(count($storefront)>=8)break;
        }
        foreach(array_keys($storefront) as $u)unset($reference[$u]);
        // Product-level generic images are allowed only when they are not known reference media.
        foreach([(string)($data['images']['thumbnail'] ?? ''),(string)($data['images']['product'] ?? '')] as $raw){$u=$this->momentec_media_url($raw);if($u!==''&&!isset($reference[$u]))$storefront[$u]=true;}
        $this->save_supplier_reference_media($product_id,'momentec',array_keys($reference));
        $ids=[];foreach(array_slice(array_keys($storefront),0,8) as $url){$id=$this->sideload($url,$product_id,'momentec');if($id)$ids[]=(int)$id;}
        $ids=array_values(array_unique($ids));
        $manual=[];foreach($product->get_gallery_image_ids() as $id)if((int)$id&&!$this->is_supplier_attachment((int)$id))$manual[]=(int)$id;
        $primary=(int)$product->get_image_id();$supplier_gallery=array_values(array_filter($ids,static fn($id)=>(int)$id!==$primary));
        $product->set_gallery_image_ids(array_values(array_unique(array_merge($supplier_gallery,$manual))));$product->save();
    }

    private function momentec_row_for_variation'''
imp = imp[:match.start()] + replacement + imp[match.end():]

# Queue only verified Momentec storefront images; reference-only assets need no media job.
old = '''            $gallery=array_values(array_filter((array)($row['gallery'] ?? [])));$primary=trim((string)($row['primary_image'] ?? ''));
            if(!$gallery&&$primary==='')continue;
            $supplier_id=trim((string)($row['unique_key'] ?? $row['supplier_sku_id'] ?? $row['sku'] ?? ''));
            $color=trim((string)($row['color'] ?? $row['catalog_color'] ?? ''));$size=trim((string)($row['size'] ?? ''));
            $variation_id=$this->find_momentec_variation($product_id,$supplier_id,$color,$size);if(!$variation_id)continue;
            update_post_meta($variation_id,'_asss_momentec_media_pending','yes');
            update_post_meta($variation_id,'_asss_variation_gallery_urls',array_values(array_unique(array_filter(array_map('esc_url_raw',$gallery)))));
'''
new = '''            $classified=$this->momentec_classify_variant_media($row);$gallery=array_values((array)$classified['storefront']);
            $supplier_id=trim((string)($row['unique_key'] ?? $row['supplier_sku_id'] ?? $row['sku'] ?? ''));
            $color=trim((string)($row['color'] ?? $row['catalog_color'] ?? ''));$size=trim((string)($row['size'] ?? ''));
            $variation_id=$this->find_momentec_variation($product_id,$supplier_id,$color,$size);if(!$variation_id)continue;
            $this->save_supplier_reference_media($variation_id,'momentec',(array)$classified['reference']);
            if(!$gallery){$this->sync_momentec_variation_media($variation_id,$row);continue;}
            update_post_meta($variation_id,'_asss_momentec_media_pending','yes');
            update_post_meta($variation_id,'_asss_variation_gallery_urls',$gallery);
'''
imp = replace_once(imp, old, new, 'Momentec queue classification')

# Background completion should not retry reference-only rows.
old = '''        $this->sync_momentec_variation_media($variation_id,$row);
        $v=wc_get_product($variation_id);
        if($v instanceof WC_Product_Variation && ($v->get_image_id() || empty($row['gallery']))){
'''
new = '''        $this->sync_momentec_variation_media($variation_id,$row);
        $v=wc_get_product($variation_id);$classified=$this->momentec_classify_variant_media($row);
        if($v instanceof WC_Product_Variation && ($v->get_image_id() || empty($classified['storefront']))){
'''
imp = replace_once(imp, old, new, 'Momentec reference-only retry')

imp_path.write_text(imp)
main_path.write_text(main)
readme_path.write_text(readme)
print('Patched Supplier Sync v2.0.17 global reference-media policy.')
